[project]
name = "ai-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.5.0",
    "flask>=3.1.0",
    "ipykernel>=6.29.5",
    "openai>=1.70.0",
    "psycopg>=3.2.6",
    "python-dotenv>=1.1.0",
]
